sudo: enabled
dist: trusty

language: node_js
node_js:
 - "node"

addons:
apt:
 sources:
 - google-chrome

before_install:
 - export CHROME_BIN=chromium-browser
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start

script:
 - ng build --target=production --environment=aws-test
 - ng serve & ng e2e
 - ng test --sourcemaps false --watch false # http://mseemann.de/frontend/2016/05/31/setup-angular-2-app-part-1.html

notifications:
  flowdock: 9290c9980054b2c50ce5f274fc949319
